### PR TITLE
Bugfix: display correct caption assigned to each image

### PR DESCRIPTION
**Pull request by PiiXiieeS**
- Inline images are displayed with small image and without caption
- Captions are always center to the images even when those are aligned to the left or the right of the page
- Horizontal lines are clearing out the float left/right of text
- Small visualization improvement video

resolves WEB-2307

### CODE REVIEW

**Comment by PiiXiieeS** [comment]
@krystiankedra 
can you take a look to this merge as it comes with certain number of changes and potential regression on the image visualization while it fixes a few defects?

**Comment by krystiankedra** [comment]
> @krystiankedra can you take a look to this merge as it comes with certain number of changes and potential regression on the image visualization while it fixes a few defects?

I will take a look today on it

**Review by krystiankedra — APPROVED** [review]
@PiiXiieeS I tested on a lot of pages those changes. Looks great and the fix for caption is awesome.

I approved.

**Comment by PiiXiieeS** [comment]
Do you have some experience on how to implement a generic NestJS middleware for this?
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=579&id=Sanofi-IADC_konviw&open=AY-XKbOYAq0d5Oa37unX

**Comment by krystiankedra** [comment]
> Do you have some experience on how to implement a generic NestJS middleware for this? https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=579&id=Sanofi-IADC_konviw&open=AY-XKbOYAq0d5Oa37unX

Hmm not yet but in some free time I will investigate about it

**Comment by PiiXiieeS** [comment]
> > Do you have some experience on how to implement a generic NestJS middleware for this? https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=579&id=Sanofi-IADC_konviw&open=AY-XKbOYAq0d5Oa37unX
> 
> Hmm not yet but in some free time I will investigate about it

Thanks @krystiankedra !
The goal would be to structure a bit better the integration of debug calls in the different steps, like the logger so we don't have to add every time an if statement and add new styles to the DOM

**Pull request merged**
