### PR TITLE
add speed unitary tests for steps

### PR DESCRIPTION
**Pull request by vlaude**

### CODE REVIEW

**Comment by vlaude** [comment]
@PiiXiieeS Here an example for speed unitary testing structure, before going further

**Review by PiiXiieeS — CHANGES_REQUESTED** [review]
I like the approach and implementation.
Just wondering how we could reuse the test cases to avoid repeating the code of the input and expected result between standard unit tests and speed tests.
Do you have some idea?

**Comment by vlaude** [comment]
> I like the approach and implementation.
> Just wondering how we could reuse the test cases to avoid repeating the code of the input and expected result between standard unit tests and speed tests.
> Do you have some idea?

I will try some design pattern implementation in order to automatically add new incoming steps into speed testing. I'll keep you updated

**Comment by vlaude** [comment]
So, I wrote a **generic test** that does the follow:
1. Setting a **HTML context** in which each step should have something to fix/do
2. Getting all the steps module inside the steps folder in the source code
3. For each step, test that 100 executions in a row are done within 10ms

What do you think about it ?

**Review by PiiXiieeS — APPROVED** [review]

**Pull request merged**
